apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skyfire-ingress
  namespace: skyfire
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: skyfire.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skyfire-api-svc
                port:
                  number: 80