apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyfire.fullname" . }}
  labels:
    {{- include "skyfire.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "skyfire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "skyfire.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: skyfire-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10